source "http://rubygems.org"
gem 'sinatra'
gem 'json'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'mysql2'
gem 'improved-rack-throttle', :git => 'git://github.com/bensomers/improved-rack-throttle.git'
gem 'annotate', :git => 'git://github.com/ctran/annotate_models.git'
gem 'activesupport'
gem 'delayed_job_active_record'
gem 'rest-client'
